import { db } from '../data/db';
import { normalizeClassName } from './utils';

export type PermissionType = 'Sakit' | 'Izin' | 'Dispensasi';
export type PermissionStatus = 'Menunggu' | 'Disetujui' | 'Ditolak';

export interface StudentPermission {
  id: string;
  studentId: string;
  studentName: string;
  studentClass: string;
  nisn?: string;
  type: PermissionType;
  startDate: string; // YYYY-MM-DD
  endDate: string;   // YYYY-MM-DD
  daysCount: number;
  reason: string;
  proofImageUrl?: string; // base64 or url
  submittedBy: 'Siswa' | 'Orang Tua' | 'Guru / Wali Kelas';
  applicantName?: string;
  applicantPhone?: string;
  submittedAt: string;
  status: PermissionStatus;
  reviewedBy?: string;
  reviewedAt?: string;
  reviewNotes?: string;
}

// Initial sample data if completely empty
const DEFAULT_PERMISSIONS: StudentPermission[] = [];

export function getPermissions(): StudentPermission[] {
  const existing = db.get<StudentPermission>('perizinan_siswa');
  if (!existing || !Array.isArray(existing) || existing.length === 0) {
    return [];
  }
  return existing;
}

export function savePermissions(list: StudentPermission[]): void {
  db.set('perizinan_siswa', list);
}

export function addPermission(permission: Omit<StudentPermission, 'id' | 'submittedAt' | 'status'>): StudentPermission {
  const list = getPermissions();
  const newPerm: StudentPermission = {
    ...permission,
    id: `perm-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
    submittedAt: new Date().toISOString(),
    status: 'Menunggu',
  };
  const updated = [newPerm, ...list];
  savePermissions(updated);
  return newPerm;
}

/**
 * Generate dates array between start and end (inclusive)
 */
export function getDatesInRange(startDate: string, endDate: string): string[] {
  const dates: string[] = [];
  const curr = new Date(startDate);
  const end = new Date(endDate);
  
  if (isNaN(curr.getTime()) || isNaN(end.getTime())) {
    return [startDate];
  }

  while (curr <= end) {
    dates.push(curr.toISOString().split('T')[0]);
    curr.setDate(curr.getDate() + 1);
  }
  return dates.length > 0 ? dates : [startDate];
}

/**
 * Approves a permission and automatically generates attendance records ('S' or 'I')
 */
export function approvePermission(id: string, reviewerName: string, notes?: string): StudentPermission[] {
  const list = getPermissions();
  const target = list.find(p => p.id === id);
  if (!target) return list;

  const updatedTarget: StudentPermission = {
    ...target,
    status: 'Disetujui',
    reviewedBy: reviewerName,
    reviewedAt: new Date().toISOString(),
    reviewNotes: notes || 'Disetujui',
  };

  const updatedList = list.map(p => p.id === id ? updatedTarget : p);
  savePermissions(updatedList);

  // Synchronize to Absensi
  syncPermissionToAbsensi(updatedTarget);

  return updatedList;
}

/**
 * Rejects a permission and removes any linked automatic attendance records
 */
export function rejectPermission(id: string, reviewerName: string, notes?: string): StudentPermission[] {
  const list = getPermissions();
  const target = list.find(p => p.id === id);
  if (!target) return list;

  const updatedTarget: StudentPermission = {
    ...target,
    status: 'Ditolak',
    reviewedBy: reviewerName,
    reviewedAt: new Date().toISOString(),
    reviewNotes: notes || 'Ditolak oleh wali kelas / sekolah',
  };

  const updatedList = list.map(p => p.id === id ? updatedTarget : p);
  savePermissions(updatedList);

  // Remove linked auto-absensi if previously approved
  removePermissionFromAbsensi(id);

  return updatedList;
}

/**
 * Syncs an approved permission to `absensi` table
 */
function syncPermissionToAbsensi(perm: StudentPermission) {
  const allAbsensi = (db.get('absensi') as any[]) || [];
  const dates = getDatesInRange(perm.startDate, perm.endDate);
  const statusLetter = perm.type === 'Sakit' ? 'S' : 'I';
  const statusLabel = perm.type === 'Sakit' ? 'Sakit' : 'Izin';

  // Filter out any existing entries for this student on these dates to prevent duplicates
  const filtered = allAbsensi.filter(a => {
    const isSameStudent = a.studentId === perm.studentId || (a.nisn && a.nisn === perm.nisn);
    const isDateOverlap = dates.includes(a.date || a.tanggal);
    return !(isSameStudent && isDateOverlap);
  });

  // Create new attendance logs for every day in range
  const newLogs = dates.map(d => ({
    id: `abs-perm-${perm.id}-${d}`,
    permissionId: perm.id,
    studentId: perm.studentId,
    name: perm.studentName,
    nama: perm.studentName,
    nisn: perm.nisn || '',
    class: perm.studentClass,
    kelas: perm.studentClass,
    date: d,
    tanggal: d,
    status: statusLetter,
    statusFull: statusLabel,
    keterangan: `[E-Izin ${perm.type}] ${perm.reason}`,
    autoGenerated: true,
    verifiedBy: perm.reviewedBy || 'Wali Kelas',
    verifiedAt: perm.reviewedAt || new Date().toISOString(),
  }));

  db.set('absensi', [...newLogs, ...filtered]);
}

/**
 * Removes attendance logs linked to a permission ID
 */
function removePermissionFromAbsensi(permissionId: string) {
  const allAbsensi = (db.get('absensi') as any[]) || [];
  const updated = allAbsensi.filter(a => a.permissionId !== permissionId);
  db.set('absensi', updated);
}

/**
 * Deletes a permission request
 */
export function deletePermission(id: string): StudentPermission[] {
  const list = getPermissions();
  const updated = list.filter(p => p.id !== id);
  savePermissions(updated);
  removePermissionFromAbsensi(id);
  return updated;
}

/**
 * Helper to compress image file or camera capture to lightweight Base64 (max ~1280px, 0.72 quality)
 */
export async function compressImageFile(file: File | Blob, maxWidth = 1280, quality = 0.72): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = (event) => {
      const img = new Image();
      img.src = event.target?.result as string;
      img.onload = () => {
        const canvas = document.createElement('canvas');
        let width = img.width;
        let height = img.height;

        if (width > maxWidth) {
          height = Math.round((height * maxWidth) / width);
          width = maxWidth;
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          resolve(event.target?.result as string);
          return;
        }
        ctx.drawImage(img, 0, 0, width, height);
        const dataUrl = canvas.toDataURL('image/jpeg', quality);
        resolve(dataUrl);
      };
      img.onerror = (err) => reject(err);
    };
    reader.onerror = (err) => reject(err);
  });
}
